#!/bin/bash

type inotifywait > /dev/null 2>&1
if [ $? -ne 0 ]
then
  cat <<EOS >&2
"inotifywait" command is required.

Run
  sudo apt-get install inotify-tools
or
  sudo yum install inotify-tools
EOS
  exit 2
fi
if [ $# -lt 1 ]
then
  cat <<EOS >&2
Usage:

  watchb COMMAND [EXCLUDE]

Examples:

  watchb "date; ls"

  watchb make ".*\\.o"

  watchb rake 'log\/test\\.log'
EOS
  exit 1
fi
COMMAND=$1

if [ $# -lt 2 ]
then
  # no EXCLUDE
  inotifywait -e create,delete,modify,move -mrq ./ | while :
  do
    messages=''
    while read -t 1 line
    do
      messages="${messages}${line} "
    done
    if [ -n "${messages}" ]
    then
      echo "DONE! `date`"
      eval $COMMAND
    fi
  done
else
  # EXCLUDE is specified
  inotifywait -e create,delete,modify,move -mrq ./ --exclude $2 | while :
  do
    messages=''
    while read -t 1 line
    do
      messages="${messages}${line} "
    done
    if [ -n "${messages}" ]
    then
      eval $COMMAND
    fi
  done
fi
